### ISSUE TITLE
Acomodar cajas al lado de otra 

### ISSUE THREAD

**Issue by MirellaLucero** [MirellaLucero/lim-2018-11-bc-core-am-data-lovers#6]
Se trato de poner un div al costado de otro con **float:left**, pero se descuadraba todo.
Se estuvo usando **flex box** y no **box model**.
Averiguar conflictos.

**Comment by claudiamalasquezaq** [comment]
Al div **card-link** le agregamos la propiedad _display: inline-block_ y agregando un _width_ de 45% para mostrar dos pokémon por línea.

Por eso se da como **Closed** este issue.

**Comment by MirellaLucero** [comment]
Listo!, agregando cambios.
